version: '3'
services:
  app:
    build:
      context: ./app
    ports:
      - '81:8000'

  pg:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "users"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./psql/data:/var/lib/postgresql/data
      - ./psql/init_scripts:/docker-entrypoint-initdb.d

  pgadmin:
    container_name: pgadmin
    depends_on:
      - pg
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: info@proglib.io
      PGADMIN_DEFAULT_PASSWORD: qwertyuiop
    expose:
      - '80'
    restart: always
  
  nginx:
    build: 
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      - app
      - pg