version: '3'
services:
  pg:
    image: postgres:15
    ports:
      - ${_PGPORT}:${_PGPORT}
    environment:
      POSTGRES_DB: ${_PGDB}
      POSTGRES_USER: ${_PGUSER}
      POSTGRES_PASSWORD: ${_PGPASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./psql/data:/var/lib/postgresql/data
      - ./psql/init_scripts:/docker-entrypoint-initdb.d
    command: -p ${_PGPORT}

  app:
    build:
      context: ./app
    ports:
      - '81:${_APP_PORT}'
      
    environment:
      PORT: ${_APP_PORT}
      # Postgres connection
      PGDB: ${_PGDB}
      PGUSER: ${_PGUSER}
      PGPASSWORD: ${_PGPASSWORD}
      PGPORT: ${_PGPORT}
      PGHOST: "pg"
      # Agora data
      APPID: ${_APPID}
      APPCERTIFICATE: ${_APPCERTIFICATE}
      
      LOG_LEVEL: "debug"
    depends_on:
      - pg


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: info@proglib.io
      PGADMIN_DEFAULT_PASSWORD: qwertyuiop
    expose:
      - '80'
    restart: always
    depends_on:
      - pg
  
  nginx:
    build: 
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      - app
      - pg