version: '3'
services:
  app:
    container_name: app
    build:
      context: ./app
    ports:
      - '5442:5442'
    environment:
      _APP_PORT: 5442
      LOG_LEVEL: 'debug'
      HOST: 'http://192.168.3.4:5442/'
      # Mysql connection
      MYSQL_USER: 'root'
      MYSQL_DB: 'users'
      MYSQL_SECRET: '123'
      MYSQL_PORT: 3306
      MYSQL_HOST: 'mysql'
      # OPENVIDU
      OPENVIDU_URL: 'https://w0m0site.freemyip.com'
      OPENVIDU_SECRET: 'secret_11'
    # restart: "on-failure:3"
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
      - ./mysql/init_scripts/:/docker-entrypoint-initdb.d/
    ports:
     - "3306:3306"
