version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./psql/data:/var/lib/postgresql/data
      - ./init_scripts/:/docker-entrypoint-initdb.d/
    ports:
     - "3306:3306"